[package]
name = "lib-tan-cmark"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "tancmark"
crate-type = ["dylib"]

[dependencies]
tan.workspace = true
comrak = { version = "0.23", default-features = false }
