[package]
name = "lib-tan-css-expr"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "tancssexpr"
crate-type = ["dylib"]

[dependencies]
tan.workspace = true
