pushd crates/lib-tan-chrono; ./install.sh; popd
pushd crates/lib-tan-cmark; ./install.sh; popd
pushd crates/lib-tan-codec-json; ./install.sh; popd
pushd crates/lib-tan-codec-uri; ./install.sh; popd
pushd crates/lib-tan-cron; ./install.sh; popd
pushd crates/lib-tan-css-expr; ./install.sh; popd
pushd crates/lib-tan-fs; ./install.sh; popd
pushd crates/lib-tan-http-client; ./install.sh; popd
pushd crates/lib-tan-html; ./install.sh; popd
pushd crates/lib-tan-http-server; ./install.sh; popd
pushd crates/lib-tan-image-png; ./install.sh; popd
pushd crates/lib-tan-regex; ./install.sh; popd
pushd crates/lib-tan-rng; ./install.sh; popd
pushd crates/lib-tan-text; ./install.sh; popd
pushd crates/lib-tan-uuid; ./install.sh; popd
