[package]
name = "lib-tan-codec-uri"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "tancodecuri"
crate-type = ["dylib"]

[dependencies]
tan.workspace = true
urlencoding = { version = "2.1" }
