[package]
name = "dummy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
rand = "0.8"
# #todo depend on more lightweight tan-api
tan = { path = "../../../tan", version = "0.14" }
