[package]
name = "lib-tan-uuid"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "tanuuid"
crate-type = ["dylib"]

[dependencies]
tan.workspace = true
uuid = { version = "1.7", features = ["v4"] }
